// The atlas pack's ten section motifs (96×96, monochrome currentColor), inlined
// so they take the colour of their surface. Used once per section identity or
// in a meaningful empty state, at 40–72 px; never on rows, cards or nodes.

const RAW = import.meta.glob('../assets/atlas/menu-emblems/*.svg', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;

export type EmblemName = 'realm-budget' | 'industry-trade' | 'military' | 'research' | 'national-focus' | 'diplomacy' | 'wars-peace' | 'victory' | 'chronicle' | 'help';

const BY_NAME = new Map(Object.entries(RAW).map(([p, svg]) => [p.replace(/^.*\//, '').replace(/\.svg$/, ''), svg]));

/** An inline emblem element (decorative: hidden from assistive technology). */
export function emblem(name: EmblemName, size = 48, cls = 'emblem'): HTMLElement {
  const span = document.createElement('span');
  span.className = cls;
  span.setAttribute('aria-hidden', 'true');
  span.style.width = `${size}px`;
  span.style.height = `${size}px`;
  span.style.display = 'inline-block';
  span.style.flex = 'none';
  // trusted, bundled SVG (generated by the pack's own build script; checked by tools/atlas-assets.ts)
  span.innerHTML = (BY_NAME.get(name) ?? '').replace(/width="96" height="96"/, `width="${size}" height="${size}"`);
  return span;
}
