// Line icons on a 24×24 grid with round 1.7-unit strokes. Most come from the
// atlas pack (src/ui/atlas-icons.gen.ts, generated by tools/atlas-assets.ts);
// the game's own shapes fill the gaps the pack leaves (dice, menu, eye, the
// build and order actions …) in the same construction. Paths are plain SVG path
// data so the map canvas can draw them via Path2D.

import { PACK_ICONS } from './atlas-icons.gen';

/** The game's own shapes, for what the pack does not draw. */
const OWN = {
  dice: 'M6 4h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2zM8.6 8.6h.01M15.4 8.6h.01M12 12h.01M8.6 15.4h.01M15.4 15.4h.01',
  wars: 'M4 4l9.5 9.5M4 4v3.2l7.8 7.8M4 4h3.2l7.8 7.8M13 17.3l4.3-4.3M20 4l-9.5 9.5M20 4v3.2l-1.6 1.6M20 4h-3.2l-1.6 1.6M11 17.3 6.7 13M6.4 18.6 4.5 20.5M17.6 18.6l1.9 1.9',
  menu: 'M4 7h16M4 12h16M4 17h16',
  battle: 'M4 4l9.5 9.5M4 4v3.2l7.8 7.8M4 4h3.2l7.8 7.8M13 17.3l4.3-4.3M20 4l-9.5 9.5M20 4v3.2l-1.6 1.6M20 4h-3.2l-1.6 1.6M11 17.3 6.7 13M6.4 18.6 4.5 20.5M17.6 18.6l1.9 1.9',
  eye: 'M2.5 12S6.2 5.5 12 5.5 21.5 12 21.5 12 17.8 18.5 12 18.5 2.5 12 2.5 12zM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z',
  chevronLeft: 'M14.5 6l-6 6 6 6',
  chevronUp: 'M6 14.5l6-6 6 6',
  move: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18zM12 3v4M12 17v4M3 12h4M17 12h4',
  build: 'M14.2 3.8 20.2 9.8l-3 3-6-6zM11.2 6.8 3.2 14.8l3 3 8-8',
  road: 'M8 3.5 4.5 20.5M16 3.5l3.5 17M12 4.5v3M12 10.5v3M12 16.5v3',
  settle: 'M3.5 20h17M6 20v-7l6-5 6 5v7M10 20v-4h4v4M12 8V3.5l4 1.5-4 1.5',
  merge: 'M6 4v5a5 5 0 0 0 5 5h7.5M18.5 14l-3-3M18.5 14l-3 3M6 20.5V14',
  split: 'M12 20.5V13M12 13 6.5 6.5M12 13l5.5-6.5M6.5 6.5V10M6.5 6.5H10M17.5 6.5V10M17.5 6.5H14',
  disband: 'M5 7h14M10 7V4.5h4V7M7 7l1 13h8l1-13',
  stop: 'M6.5 6.5h11v11h-11z',
  star: 'M12 3.5l2.6 5.4 5.9.8-4.3 4.1 1 5.9L12 16.9l-5.2 2.8 1-5.9L3.5 9.7l5.9-.8z',
  info: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18zM12 11v6M12 7.6v.01',
  plus: 'M12 5v14M5 12h14',
  minus: 'M5 12h14',
  compass: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18zM15.5 8.5l-2.2 4.8-4.8 2.2 2.2-4.8z',
  target: 'M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16zM12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM12 12v.01',
  flag: 'M5.5 21V4M5.5 4.5h12l-2.2 4 2.2 4h-12',
  alliance: 'M8.5 4.5 3.5 7v4.5c0 3.6 2.2 6 5 7 2.8-1 5-3.4 5-7V7zM15.5 4.5l5 2.5v4.5c0 3.6-2.2 6-5 7',
  claim: 'M5.5 20.5 12 4l6.5 16.5M8.2 14h7.6',
  hourglass: 'M6.5 3.5h11M6.5 20.5h11M7.5 3.5c0 4.5 4.5 5.5 4.5 8.5s-4.5 4-4.5 8.5M16.5 3.5c0 4.5-4.5 5.5-4.5 8.5s4.5 4 4.5 8.5',
  scroll: 'M7.5 4H18a2 2 0 0 1 2 2v1.5h-4M16 7.5V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-1.2h9.5M7.5 4a2 2 0 0 0-2 2v10.8',
  keyboard: 'M3 7h18v10H3zM6.5 10.5h1M10 10.5h1M13.5 10.5h1M17 10.5h.5M7.5 14h9',
  sound: 'M4 9.5h3.5L12 5.5v13l-4.5-4H4zM15.5 9a4.5 4.5 0 0 1 0 6M18 6.5a8 8 0 0 1 0 11',
  mine: 'M4.5 19.5 13.5 10.5M11.8 5.3c2.9-1.2 5.8-.8 7.6 1.1-1.5-.6-3.3-.5-4.8.4M18.7 12.2c1.2-2.9.8-5.8-1.1-7.6.6 1.5.5 3.3-.4 4.8M12.2 6.2l5.6 5.6',
} as const;

/** The game's icon names that the pack draws (same meaning, pack shape). */
const P = PACK_ICONS;
const FROM_PACK = {
  crown: P.realm,
  treasury: P.treasury,
  supplies: P.food,
  manpower: P.manpower,
  research: P.research,
  policy: P.focusTree,
  diplomacy: P.diplomacy,
  victory: P.victory,
  chronicle: P.chronicle,
  military: P.army,
  help: P.help,
  settings: P.settings,
  play: P.play,
  pause: P.pause,
  step: P.step,
  zoomIn: P.zoomIn,
  zoomOut: P.zoomOut,
  fit: P.fitWorld,
  capital: P.capital,
  army: P.army,
  bell: P.notification,
  layers: P.layers,
  political: P.province,
  terrain: P.terrain,
  supply: P.supply,
  economy: P.economy,
  relations: P.diplomacy,
  threat: P.warning,
  alert: P.warning,
  close: P.close,
  chevronRight: P.chevronRight,
  chevronDown: P.chevronDown,
  fort: P.fortification,
  charter: P.contract,
  check: P.check,
  save: P.save,
  upload: P.import,
  download: P.export,
  pact: P.defend,
  trade: P.trade,
  envoy: P.envoy,
  factory: P.industry,
  materiel: P.equipment,
  globe: P.atlas,
  ship: P.warship,
  plane: P.airForce,
  anchor: P.navy,
} as const;

export const ICONS = { ...OWN, ...PACK_ICONS, ...FROM_PACK } as const;


export type IconName = keyof typeof ICONS;

const SOLID = new Set<IconName>(['star']);
const NS = 'http://www.w3.org/2000/svg';

/** An inline SVG icon element (inherits currentColor). */
export function icon(name: IconName, cls = ''): SVGSVGElement {
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('class', `ico ${SOLID.has(name) ? 'solid' : ''} ${cls}`.trim());
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  const p = document.createElementNS(NS, 'path');
  p.setAttribute('d', ICONS[name]);
  svg.appendChild(p);
  return svg;
}

const pathCache = new Map<IconName, Path2D>();
/** The icon as a Path2D in its 24×24 space (for drawing on the map canvas). */
export function iconPath(name: IconName): Path2D {
  let p = pathCache.get(name);
  if (!p) {
    p = new Path2D(ICONS[name]);
    pathCache.set(name, p);
  }
  return p;
}
